2019-06-05T09:53:54|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "microscope_app.py", line 33, in <module>
    app = OceanOpticsApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "microscope_app.py", line 16, in setup
    from PiezoStage_hardware import PiezoStageHW
  File "C:\Users\lindat18\Dropbox\Ginger_Lab\HW_OceanOptics\PiezoStage_hardware.py", line 27
    self.pi_device = GCSDevice("E-710")	# Creates a Controller instant
                                       	                             ^
TabError: inconsistent use of tabs and spaces in indentation

